apiVersion: v1
kind: Service
metadata:
  name: usuario-service-cmd
  namespace: neargrocery-development
  labels:
    app: usuario-service-cmd
    version: "1.0"
    environment: development
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9999
      protocol: TCP
      name: http
  selector:
    app: usuario-service-cmd
    version: "1.0"
    environment: development
